# Auto-generated by /home/yurchenko_v/workspace/tianocore-mcst/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/yurchenko_v/workspace/tianocore-mcst
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/yurchenko_v/workspace/tianocore-mcst/BaseTools
fi
if [ -e /home/yurchenko_v/workspace/tianocore-mcst/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/yurchenko_v/workspace/tianocore-mcst/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/yurchenko_v/workspace/tianocore-mcst/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
